object Versions {
    const val core = "1.10.0"
    const val material = "1.9.0"
    const val constraint = "2.1.4"
    const val appCompat = "1.6.1"
    const val application = "7.4.2"
    const val library = "7.4.2"
    const val kotlinAndroid = "1.7.20"
    const val coroutines = "1.6.4"
    const val navigation = "2.5.3"
    const val retrofit = "2.9.0"
    const val safeArgs = "2.5.3"
    const val kotlinJvm = "1.8.0"
    const val lifecycles = "2.6.1"
    const val hilt = "2.45"
    const val gson = "2.9.0"
    const val fragment = "1.5.7"
    const val glide = "4.15.0"
    const val viewBindingPropertyDelegate = "1.5.3"
    const val okHttpBom = "5.0.0-alpha.6"
    const val viewPager = "1.1.0-beta02"
    const val viewPagerLegacySupport = "1.0.0"
}